### ISSUE TITLE
less-grpc-reality无法使用

### ISSUE THREAD

**Issue by Skylush** [eooce/xray-2go#1]
一键生成的vless-grpc-reality无法使用，我还需要排查些什么
<img width="807" alt="image" src="https://github.com/user-attachments/assets/a82a536c-824d-4bf0-8d90-1ef37d2f0a79">
<img width="805" alt="image" src="https://github.com/user-attachments/assets/0501edce-d17d-42c3-bc47-96928628af13">

**Comment by eooce** [comment]
reality是直连节点，你ipv6的机子，本地网络得有ipv6才支持的，否则就应其他的三个argo节点，手机卡的网络一般都有ipv6，可以直接用

**Comment by Skylush** [comment]
本地有ipv6

eooce ***@***.***> 于2024年10月7日周一 03:40写道：

**Comment by eooce** [comment]
端口默认应该不是443，你使用的443肯定是不通的，用给的节点链接导入
